# Generated by Django 4.2 on 2024-08-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.ImageField(upload_to='file1')),
                ('file2', models.ImageField(upload_to='file2')),
            ],
        ),
    ]
