# Generated by Django 5.1.1 on 2024-09-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='file2',
            field=models.URLField(),
        ),
    ]
